// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcelBox.Api.Database;

#nullable disable

namespace ParcelBox.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205223539_AddParcelDbContext")]
    partial class AddParcelDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParcelBox.Api.Model.Locker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lockers");
                });

            modelBuilder.Entity("ParcelBox.Api.Model.LockerBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<int>("LockerId")
                        .HasColumnType("integer");

                    b.Property<int>("LockerSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LockerId");

                    b.ToTable("LockerBoxes");
                });

            modelBuilder.Entity("ParcelBox.Api.Model.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitialLockerBoxId")
                        .HasColumnType("integer");

                    b.Property<int>("InitialLockerId")
                        .HasColumnType("integer");

                    b.Property<int>("ParcelSize")
                        .HasColumnType("integer");

                    b.Property<string>("PickupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetLockerBoxId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLockerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("ParcelBox.Api.Model.LockerBox", b =>
                {
                    b.HasOne("ParcelBox.Api.Model.Locker", "Locker")
                        .WithMany("LockerBoxes")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locker");
                });

            modelBuilder.Entity("ParcelBox.Api.Model.Locker", b =>
                {
                    b.Navigation("LockerBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
